apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{  .Chart.Name }}-config"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
data:
  MONGO_REMOTE_URL: "mongodb://169.57.160.83:27017"
  MONGO_LOCAL_URL: ""  